"""empty message

Revision ID: 981aa984ae6a
Revises: ee241bad151e
Create Date: 2024-11-06 14:12:32.904332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981aa984ae6a'
down_revision = 'ee241bad151e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
